[package]
name = "dalvik"
version = "0.1.0"
edition = "2021"

[dependencies]
dalvikcommon = { path = "dalvikcommon" }
dalvikdex = { path = "dalvikdex" }
dalvikvm = { path = "dalvikvm" }
dalvikruntime = { path = "dalvikruntime" }
